### ISSUE TITLE
Possibility to introduce quantization?

### ISSUE THREAD

**Issue by abagshaw** [thtrieu/darkflow#143]
Not trying to fill up the feature request queue even further - but just putting it out there: Would it be possible to introduce some form of quantization in darkflow to reduce memory usage, increase prediction speed at the expense of a little accuracy?

https://www.tensorflow.org/performance/quantization

I really don't know how all of this works so maybe quanitization wouldn't even be applicable or have any appreciable benefits to darkflow - but every little bit of performance improvement and memory usage reduction counts!

**Comment by abagshaw** [comment]
I've spent some time looking into this. One solution I was thinking of was creating a `.pb` file from the `.weights` and `.cfg` files, then quantizing that model using the tool outlined in the page linked in my original post and then finally loading that quantized `.pb` file back into darkflow for running predictions.

This seems a little roundabout to me (again I don't know if quantization would have any positive affects on darkflow's performance - I'm just experimenting :) ) but @thtrieu is there some better way to do this? Not trying to add something more to your plate - I'm sure you're super busy and I'm happy to chip away at this problem on my own - just wondering if you have any suggestions.

Thanks so much!

**Comment by thtrieu** [comment]
I don't know anything about quantization. Would need some time to read about that! But just keep doing what you are doing, I'm sure some body would need that some day.

**Comment by AndreaPisoni** [comment]
Why do you say this is roundabout? First you get your ckpt files which are good for training. Once you want to put your system into production you usually want to load from a pb file, and if you want to quantize it you can use the tool.

**Comment by abagshaw** [comment]
Well, I've implemented loading from .pb into darkflow - and that works just fine -  I'll have to clean the code up before I submit a pull request.

Two things:
1. There are a bunch of variables in the `meta` dictionary like `out_size`, `classes`, `anchors`, etc. that are loaded (or determined) from the .cfg file and necessary for post-processing. I think it would be a little cumbersome to have to keep the .cfg file tagging around alongside the .pb file just so darkflow can figure out those variables for post processing. My solution at the moment was to dump everything in `meta` into a file like `yolo-tiny.meta` when running `savepb()` that would be kept alongside the .pb file and then everything could be loaded back into the `meta` variable straight from the `yolo-tiny.meta` file when using the .pb file. This also takes care of the label names so you don't have to keep the `coco.names` file hanging around as well (if that's the names file that corresponds to the .weights file you are using). What I am wondering is if there's a way to embed this information into the .pb file to have everything nicely packaged up into one file. I posted a question on SO: http://stackoverflow.com/questions/43298228/write-additional-variables-to-tensorflow-pb-file

2. I don't seem to be able to get the quantization process to work on the `yolo.pb` file produced from `yolo.weights` and `yolo.cfg`. I enter `output` as the output tensor but I get an error. Someone suggested here https://github.com/tensorflow/tensorflow/issues/8347 that the `KeyError` may be a result of getting the output tensor name wrong - but I don't think I've gotten it wrong, have I? I don't suppose any of you would have any ideas on why the quantization is failing...I'm assuming it's a bug in the quantization script, but if you have any ideas - let me know.

Thanks!

**Comment by AndreaPisoni** [comment]
Check what the system is expecting to see in input/output with 

bazel build tensorflow/tools/graph_transforms:summarize_graph
bazel-bin/tensorflow/tools/graph_transforms/summarize_graph --in_graph=your_graph.pb

**Comment by AndreaPisoni** [comment]
About question 1.. if these parameters that you have are constant, then you should use constant nodes in the graph def and use them to feed the nodes that are using those parameters. If those are variable, then it is much better to have a separate config file, it is not that cumbersome, come on ;)

BTW, out_size, classes, anchors seem to be parameters used to build the graph rather than set at run time... so it is definitely possible to just set them at training and preserve them in the net architecture

**Comment by abagshaw** [comment]
@AndreaPisoni Regarding getting quantization to work and finding input and output tensors - I generated a visual representation of the graph using TensorBoard, see https://1drv.ms/i/s!Apz4yDTPjBAehfE9HnptOsOyqmVM_w

Are you able to tell what the input and output tensors are from that image? I don't have bazel so I don't seem to be able to run the summarize_graph tool.

**Comment by borasy** [comment]
Is there any progress for making quantization to work?? I would really appreciate it if someone can make it. Thanks

**Comment by ashwinnair14** [comment]
@abagshaw Have you made any progress on this ?? It would be awesome to have this work on a Raspberry Pi with a few fps.

**Comment by chyacinth** [comment]
Hi, I have been working on quantization recently, and I found that KeyError occurs when you use eightbit quantization mode. The problem is caused by [https://github.com/tensorflow/tensorflow/blob/abd5375ba8d373045321d1eebdb4501c36ab0ccd/tensorflow/tools/quantization/quantize_graph.py#L411](url). It seems that the output node is removed by the remove_training_nodes function. Take a closer look at that function in [https://github.com/tensorflow/tensorflow/blob/4172ca2cd7ac34be67bda2600944d284e8907b95/tensorflow/python/framework/graph_util_impl.py#L289](url), I find that the output node is not recognized as control edge (not sure what that means, I' m a newbie to Tensorflow). I let has_control_edge be True when the node is output, and the quantization script runs normally (not sure if it is the right way to tackle this problem). The result eightbit quantization version of YOLO shows some capability of detecting objects, but is not quite robust. Hope this will help people who are working on this problem.

**Comment by el3ctrician** [comment]
hello, i am redoing the whole process to test it myself, how can i get the input/output tensors name ?
thanks

**Comment by el3ctrician** [comment]
so i generated a quantized model using --savepb flag and then without freezing giving the pb generated file to the graph transform tool from (https://github.com/tensorflow/tensorflow/blob/master/tensorflow/tools/graph_transforms/README.md) and applied the quantize weight transform. I loaded then my model to flow using loadpb and but i get much worse preformance.. any thoughts ?
