### ISSUE TITLE
Reducing Yolo 2 size

### ISSUE THREAD

**Issue by anonym24** [thtrieu/darkflow#177]
I have  successfully run app with tiny yolo .pb model - https://github.com/tensorflow/tensorflow/issues/9343

But I cannot run Yolo 2 (graph-yolo-voc.pb - 193mb).
Can we reduce .pb file somehow, for example clear everything beside person from original weights,
so it become less size and could detect only people.

Is it possible?

**Comment by Momotyust** [comment]
Hi
@anonym24 , I am a beginner and trying to do the same thing as you. I have created a tiny-yolo-voc.pb model successfully. Now I try to verify this model using python and want to transplant it to Android. Could you give me some advice about what you have done?

**Comment by anonym24** [comment]
@Momotyust don't really understand what are you trying to do `the same thing as you`
I've make .pb tiny, put it to android assets folder and changed 'use yolo boolean field' to true in detector activity and it worked good, if that what you want. 
But I have a problem with yolo 2 .pb, because its size much bigger (193mb) and I can't run it on phone, I get OutOfMemory error - https://github.com/tensorflow/tensorflow/issues/9343#issuecomment-296095974

**Comment by abagshaw** [comment]
Quantization may be able to help in terms of reducing the `.pb` size. See https://github.com/thtrieu/darkflow/issues/143 (I'm trying to get this working).

**Comment by thtrieu** [comment]
Several strategies to reduce the model usage of memory: research-wise, one can redesign a smaller model at the cost of lowering accuracy. Engineering-wise, one can try 16bit floating points. Quantization is another thing. There are several other strategies that I do not know.

I am no expert in model size reduction. Hopefully someone else can come to offer systematic reduction strategies applicable for a wide range of mobile applications, not just YOLO.

In the meantime, seek help somewhere else since this issue seems inactive.
