### ISSUE TITLE
Initialize weights

### ISSUE THREAD

**Issue by EngShaheen** [thtrieu/darkflow#20]
I'm trying to train yolo v1.1 on my own data of two classes
I made a copy of `yolov1.cfg` file and changed the output of the `connected` layer to 833
according to this formula
(5 x num + number_of_classes) x side x side
where num = 3 and side = 7 in the cfg file of yolov1
I downloaded yolo.weights file of size 789 MB as mentioned in the `README.md` file
but I got this error
![er](https://cloud.githubusercontent.com/assets/16343109/21484582/b305f208-cb9d-11e6-8ca3-b8fb7668c45a.JPG)

p.s. I used an old version of this repo before, to train my data on a yolov1.0 model successfully 
and it had `genw.py` file to initialize the weights of the 2 classes model with weights of a pre-trained one

but I don't know how to initialize weights now

**Comment by thtrieu** [comment]
Since the `.cfg` name is identical to that of the `weights` file name, the program thinks these two are of the same model and expect the size indicated by `.cfg` to match that of `.weights`. So you can solve this by simply change the name of your `.cfg` to a new name to avoid confusions.

Tell me if that works :)

**Comment by EngShaheen** [comment]
but the names are already different !
`yolov1-2c.cfg` and `yolo.weights`

**Comment by thtrieu** [comment]
Where do you put `yolov1.cfg` ? Because the program needs to understand both the old and new configuration in order to initialize the new from the old. If you are not specify anything further in your command, the program will look for `yolov1.cfg` inside `./cfg/` and I think it was not there (may be `./cfg/v1.1/` or something?). You can set the default folder of config by option `--config`.

The best way is tell me precise steps to reproduce the problem instead of just posting the error, because with only clues like this I was just guessing!

**Comment by EngShaheen** [comment]
Thanks for the replay, and sorry for any confusion 
I specified the directory of the cfg file and the weights in the command
as shown in the first line in the image that I posted in the first comment
(sorry, I forgot to mention that the command is shown in the image)

Here is what I did so it may help to reproduce the error 
I made a copy of `yolov1.cfg` file and **named it** `yolov1-2c.cfg` then changed the output of the connected layer to 833 (according to the formula in the first comment)
and I put it in the same directory of the yolov1.1 config file `./cfg/v1.1/` 
then I downloaded the yolov1.1 weights and the file name is `yolo.weights` and I put it in `./bin/` directory

then I used this command
`./flow --model cfg/v1.1/yolov1-2c.cfg --load bin/yolo.weights`

I appreciate your efforts and this repo is very useful and helped me so much.

**Comment by thtrieu** [comment]
I expect this error for the reason stated in my previous reply. I suggest using the following command

`./flow --mode cfg/v1.1/yolov1-2c.cfg --load bin/yolo.weights --config cfg/v1.1/`

**Comment by EngShaheen** [comment]
I tried the command but still have the same error
`AssertionError: expect 745054228 bytes, found 789312988`

**Comment by thtrieu** [comment]
@EngShaheen  Please change `yolo.weights`'s name to `yolov1.weights` and use

```
./flow --mode cfg/v1.1/yolov1-2c.cfg --load bin/yolo.weights --config cfg/v1.1/
```

Because using the name `yolo.weights`, there is no way `darkflow` will understand the corresponding config is `cfg/v1.1/yolov1.cfg`, in fact, it will look for `cfg/yolo.cfg` and raise the error.

Hope this helps.

**Comment by EngShaheen** [comment]
It worked and could initialize weights successfully 
but I got a new error
![er](https://cloud.githubusercontent.com/assets/16343109/21544199/bc070bbe-cdd5-11e6-9c68-74cb68d62f08.JPG)

`TypeError: batch_norm() got an unexpected keyword argument 'initializers'`

**Comment by thtrieu** [comment]
I think this should not be an error in my new commit. This parameter `initializers` is changed to `param_initializers`.
