### ISSUE TITLE
weights for models

### ISSUE THREAD

**Issue by aivision2020** [thtrieu/darkflow#24]
I'm confused, I'm sure this is a silly question. Where are the .weights files?
specifically I'm looking for the coco models

Thanks!

**Comment by thtrieu** [comment]
Weights file are here http://pjreddie.com/darknet/yolo/
Look around for older version

**Comment by rtrahms** [comment]
Do you have to keep the cfg and weights files paired?  I would assume so.  For example, I wouldn't use one of the darkflow cfg files and one of the pjreddie/darknet/yolo weight files, right?

**Comment by thtrieu** [comment]
As long as `--model`, `--load` and `--config` is pointing to appropriate position, the pair `.cfg` and `.weights` are well-defined and there will be no confusion. An example:

```python
./flow --model ~/darkflow/cfg/yolo.cfg --load ~/pjreddie/darknet/yolo.weights
# or partially load yolo-4c from yolo.weights, assuming yolo.weights' cfg is at ~/somewhere/
./flow --model ~/darkflow/cfg/yolo-4c.cfg --load ~/pjreddie/darknet/yolo.weights --config ~/somewhere/
```

**Comment by rtrahms** [comment]
Good to know about the --config flag.  I tried a test, using the darkflow tiny cfg, and the V1 tiny cfg and weights.
Got an assertion error:

rob@skynet1:~/darkflow$ ./flow --model cfg/v1/yolo-tiny.cfg --train --load /home/rob/models_darknet/yoloV1_tiny/tiny-yolo.weights --config /home/rob/models_darknet/yoloV1_tiny/tiny-yolo.cfg --dataset /home/rob/Data_PascalVOC/VOCdevkit/VOC2012/JPEGImages/ --annotation /home/rob/Data_PascalVOC/VOCdevkit/VOC2012/Annotations/ --gpu 1.0
I tensorflow/stream_executor/dso_loader.cc:120] successfully opened CUDA library libcublas.so.8.0 locally
I tensorflow/stream_executor/dso_loader.cc:120] successfully opened CUDA library libcudnn.so.5 locally
I tensorflow/stream_executor/dso_loader.cc:120] successfully opened CUDA library libcufft.so.8.0 locally
I tensorflow/stream_executor/dso_loader.cc:120] successfully opened CUDA library libcuda.so.1 locally
I tensorflow/stream_executor/dso_loader.cc:120] successfully opened CUDA library libcurand.so.8.0 locally
Parsing cfg/v1/yolo-tiny.cfg
Loading /home/rob/models_darknet/yoloV1_tiny/tiny-yolo.weights ...
Traceback (most recent call last):
  File "./flow", line 42, in <module>
    tfnet = TFNet(FLAGS)
  File "/home/rob/darkflow/net/build.py", line 34, in __init__
    darknet = Darknet(FLAGS)
  File "/home/rob/darkflow/dark/darknet.py", line 26, in __init__
    self.load_weights()
  File "/home/rob/darkflow/dark/darknet.py", line 78, in load_weights
    wgts_loader = loader.create_loader(*args)
  File "/home/rob/darkflow/utils/loader.py", line 104, in create_loader
    return load_type(path, cfg)
  File "/home/rob/darkflow/utils/loader.py", line 18, in __init__
    self.load(*args)
  File "/home/rob/darkflow/utils/loader.py", line 69, in load
    val = walker.walk(new.wsize[par])
  File "/home/rob/darkflow/utils/loader.py", line 126, in walk
    'Over-read {}'.format(self.path)
AssertionError: Over-read /home/rob/models_darknet/yoloV1_tiny/tiny-yolo.weights

Looking through what over-read means right now...

**Comment by rtrahms** [comment]
BTW, pulling both --weights and --config arguments out of the above call (starting from scratch weights basically) allows training to start fine.

**Comment by thtrieu** [comment]
Your command:
```
./flow --model cfg/v1/yolo-tiny.cfg --load /home/rob/models_darknet/yoloV1_tiny/tiny-yolo.weights --config /home/rob/models_darknet/yoloV1_tiny/tiny-yolo.cfg
```
Is invalid, as `--config` should be a folder, to look for `tiny-yolo.cfg`, not the specific file, so the correct command is 

```
./flow --model cfg/v1/yolo-tiny.cfg --load /home/rob/models_darknet/yoloV1_tiny/tiny-yolo.weights --config /home/rob/models_darknet/yoloV1_tiny/
```

**Comment by rtrahms** [comment]
I *think* I figured it out.  I tried the above call using **--binary** and **--config** flags, and training is now running.  Is the --load argument only used for checkpoints?

**Comment by rtrahms** [comment]
Same error, using --config with folder instead of file.  Error below.

rob@skynet1:~/darkflow$ ./flow --model cfg/v1/yolo-tiny.cfg --train --load /home/rob/models_darknet/yoloV1_tiny/tiny-yolo.weights --config /home/rob/models_darknet/yoloV1_tiny/ --dataset /home/rob/Data_PascalVOC/VOCdevkit/VOC2012/JPEGImages/ --annotation /home/rob/Data_PascalVOC/VOCdevkit/VOC2012/Annotations/ --gpu 1.0
I tensorflow/stream_executor/dso_loader.cc:120] successfully opened CUDA library libcublas.so.8.0 locally
I tensorflow/stream_executor/dso_loader.cc:120] successfully opened CUDA library libcudnn.so.5 locally
I tensorflow/stream_executor/dso_loader.cc:120] successfully opened CUDA library libcufft.so.8.0 locally
I tensorflow/stream_executor/dso_loader.cc:120] successfully opened CUDA library libcuda.so.1 locally
I tensorflow/stream_executor/dso_loader.cc:120] successfully opened CUDA library libcurand.so.8.0 locally
Parsing /home/rob/models_darknet/yoloV1_tiny/tiny-yolo.cfg
Parsing cfg/v1/yolo-tiny.cfg
Loading /home/rob/models_darknet/yoloV1_tiny/tiny-yolo.weights ...
Traceback (most recent call last):
  File "./flow", line 42, in <module>
    tfnet = TFNet(FLAGS)
  File "/home/rob/darkflow/net/build.py", line 34, in __init__
    darknet = Darknet(FLAGS)
  File "/home/rob/darkflow/dark/darknet.py", line 26, in __init__
    self.load_weights()
  File "/home/rob/darkflow/dark/darknet.py", line 78, in load_weights
    wgts_loader = loader.create_loader(*args)
  File "/home/rob/darkflow/utils/loader.py", line 104, in create_loader
    return load_type(path, cfg)
  File "/home/rob/darkflow/utils/loader.py", line 18, in __init__
    self.load(*args)
  File "/home/rob/darkflow/utils/loader.py", line 69, in load
    val = walker.walk(new.wsize[par])
  File "/home/rob/darkflow/utils/loader.py", line 126, in walk
    'Over-read {}'.format(self.path)
AssertionError: Over-read /home/rob/models_darknet/yoloV1_tiny/tiny-yolo.weights

**Comment by rtrahms** [comment]
Seems like it is getting hung up on parsing the darknet weights file.  Incidentally, would using the --binary flag work, instead of the --load flag?

**Comment by thtrieu** [comment]
The message means `home/rob/models_darknet/yoloV1_tiny/tiny-yolo.cfg` indicates a larger size than `/home/rob/models_darknet/yoloV1_tiny/tiny-yolo.weights` actually is.

**Comment by rtrahms** [comment]
Okay, interesting.  Might be a problem with the files I pulled from the darknet site.
I suspected something similar, tried a different set (tiny_extract), with V1 extraction cfg and weights, and seems to work okay.

**Comment by rtrahms** [comment]
Possibly.  I'll take another look to make sure I'm using the correct pairing.

**Comment by QueenJuliaZxx** [comment]
hi,you,when I want to train a new model Iues the order:
./flow --model cfg/v3/tiny-yolo-voc-3c.cfg --load bin/tiny-yolo-voc.weights 
#######tiny-yolo-voc is a copy of tiny-yolo-voc and class=3,filter=40,and label.txt include 3 class###
It come out a problem like this:
AssertionError: expect 63123056 bytes, found 63471556
I know it caused by the unpair between  the .weight and .cfg ,how to solve this problem
thank you!
