### ISSUE TITLE
Result is different between darknet and darkflow

### ISSUE THREAD

**Issue by duseok** [thtrieu/darkflow#25]
### Run
```
$./darknet detector test -gpus 0,1 cfg/voc.data cfg/tiny-yolo-voc.cfg /data/dark_backup/tiny-yolo-voc_final.weights data/person.jpg
```
### Inference result from darknet
![darknet](https://cloud.githubusercontent.com/assets/14088166/21636143/d270a01c-d2a4-11e6-9d6e-58f80edd67ca.png)

### Run
```
$./flow --test test/ --model ~/workspace/darknet/cfg/tiny-yolo-voc.cfg --load /data/dark_backup/tiny-yolo-voc_final.weights --gpu 1.0
```
### Inference result rom darkflow
![darkflow](https://cloud.githubusercontent.com/assets/14088166/21636151/df98b946-d2a4-11e6-9303-224ff81fd4b9.jpg)

I wonder why these two images show different output. Is there anything I missed?

thanks in advance!

**Comment by thtrieu** [comment]
Even me got a different result for the same model running `darkflow`

![person](https://cloud.githubusercontent.com/assets/9194247/21636772/79381b96-d296-11e6-8932-24b823792a72.jpg)

It might be due to the difference between the implementation of ops kernel on the specific hardware. Rounding errors, handle of overflow/underflow, etc. This is something I must do more research to answer correctly, but I expect this kind of difference since we are using the weights trained on `darknet` and use it verbatim on `tensorflow`.
