### ISSUE TITLE
How to fine-tune?

### ISSUE THREAD

**Issue by 9thDimension** [thtrieu/darkflow#29]
Firstly, let me say thanks and congratulations on this ambitious and impressive project.

I've been perusing the code-base and I don't understand it very well. I would like to fine-tune YOLO to my own dataset, using a checkpoint that was learnt on VOC/COCO data.

Just as a test-run, to see what would happen, I ran

`./flow --train --model cfg/tiny-yolo.cfg --load bin/tiny-yolo.weights`

which came back with the error:

 ```
...
 Load  |  Yep!  | conv 3x3p1_1  +bnorm  leaky      | (?, 13, 13, 1024)
 Load  |  Yep!  | conv 3x3p1_1  +bnorm  leaky      | (?, 13, 13, 1024)
 Load  |  Yep!  | conv 1x1p0_1    linear           | (?, 13, 13, 425)
-------+--------+----------------------------------+---------------
Running entirely on CPU
Traceback (most recent call last):
  File "./flow", line 42, in <module>
    tfnet = TFNet(FLAGS)
  File "/home/hal9000/Sources/darkflow/net/build.py", line 51, in __init__
    self.setup_meta_ops()
  File "/home/hal9000/Sources/darkflow/net/build.py", line 94, in setup_meta_ops
    if self.FLAGS.train: self.build_train_op()
  File "/home/hal9000/Sources/darkflow/net/help.py", line 15, in build_train_op
    self.framework.loss(self.out)
  File "/home/hal9000/Sources/darkflow/net/vanilla/train.py", line 9, in loss
    'Loss type {} not implemented'.format(loss_type)
AssertionError: Loss type [region] not implemented

```

So I ask:

(1) Which options on the flow shell script do I need to run fine-tuning?
(2) How do I point to my dataset, and how should it be formatted?

Thanks again.

**Comment by thtrieu** [comment]
(1) You did it correctly, the only reason you cannot fine-tune this config is because it is YOLO9000, for which I did not build the training part (as stated in README). If you want to fine-tune older version's configs, point to `./cfg/v1/` or `./cfg/v1.1/`

(2) use option `--dataset` and `--annotation`, you can see the complete set of options by `./flow --h` (again, as stated in README). The format should be identical to that of PASCAL VOC dataset.
