### ISSUE TITLE
file summing up when running video demo

### ISSUE THREAD

**Issue by zinkcious** [thtrieu/darkflow#516]
Hello, I'm using this project to detect people in the video, because there are lots of videos, I find that a folder named 'train' under 'summary' folder will be created and lots of files will be generated under that folder. I don't want those files to be generated, any one knows which part of the code generates the files?

**Comment by SkullPirateTK** [comment]
In [https://github.com/thtrieu/darkflow/blob/master/darkflow/defaults.py](url), change `self.define('summary', './summary/', 'path to TensorBoard summaries directory')` to `self.define('summary', None, 'path to TensorBoard summaries directory')`.

**Comment by abagshaw** [comment]
@SkullPirateTK Thanks for the workaround. A fix has been implemented now, though, so that shouldn't be necessary any more (now any "falsy" value for `summary` disables TensorBoard logging).

As of https://github.com/thtrieu/darkflow/pull/518, TensorBoard logging is now _disabled_ by default (as it probably should have been from the beginning).

**Comment by zinkcious** [comment]
Thanks very much!
