### ISSUE TITLE
Different output from original code (darknet)

### ISSUE THREAD

**Issue by wkentaro** [thtrieu/darkflow#62]
The result looks different from original code.
Anyone have idea how to fix this? I'm relatively new to darkflow.

**darkflow**

![dog](https://cloud.githubusercontent.com/assets/4310419/23136178/d1037e2a-f7de-11e6-8334-8f0514529330.jpg)

**darknet**
![predictions_dog_darknet](https://cloud.githubusercontent.com/assets/4310419/23136281/5b9a775a-f7df-11e6-883e-ae0a16404df9.jpg)

**Comment by hungpt297** [comment]
Same problem with yolo v2, used weight file: http://pjreddie.com/media/files/yolo.weights

**Comment by jiangsutx** [comment]
I found one difference that this Darkflow uses epsilon=1e-5 for batch_norm (in convolutional.py)
But in original darknet source code, they uses 0.000001 which is 1e-6. 
I am testing to see it is the problem.

Another possible difference is that Darkflow uses cv2.imread to load image, and then cv2.resize to resize it using default parameters on UINT8 images.(in net/yolo/test.py preprocessing)
This may cause some tiny differences if darknet uses other function.

I am still trying to find the problem here.

**Comment by thtrieu** [comment]
Wow thanks! I am fixing this ASAP.

**Comment by MisayaZ** [comment]
@jiangsutx  I am interested in your light version of YOLO V2

**Comment by crazylyf** [comment]
@jiangsutx  Any evaluation on the influence of all those possible reasons?

**Comment by jiangsutx** [comment]
@crazylyf The nms bug is the main problem. imresize() also influence the results. Other differences may not that important.

**Comment by crazylyf** [comment]
@jiangsutx Okay, thank you! Is there any experiment comparing the mAP on VOC or COCO dataset?

**Comment by jiangsutx** [comment]
@crazylyf No. I am not an expert in Detection. I only want to use it in my other system. : )
Please let me know, if you have any updates. Thank you.

**Comment by crazylyf** [comment]
@jiangsutx  I'm not familiar with tensorflow. Instead, I'm trying to find out the discrepancy between original darknet and pytorch version of yolo2 [yolo2-pytorch](https://github.com/longcw/yolo2-pytorch).
