### ISSUE TITLE
Yolov2.weight not found in python(atom)

### ISSUE THREAD

**Issue by H4k4n61** [thtrieu/darkflow#693]
I use Windows 10. I install YOLOv2 608x608 weights in [link](https://pjreddie.com/darknet/yolo/) . After that I pasted it into the bin file. I use cmd and run `python flow --model cfg/yolo.cfg --load bin/yolov2.weights --demo deneme.mp4 --gpu 0.4 --saveVideo` this is work. After that set up atom and run 
`import cv2
from darkflow.net.build import TFNet
import numpy
option = {
    'model': 'cfg/yolo.cfg',
    'load': 'bin/yolov2.weights',
    'threshold': 0.15,
    'gpu': 0.5
}

tfnet = TFNet(option) `
This give error 
Traceback (most recent call last):
  File "C:\Users\Hakan\Desktop\object\darkflow-master\figure.py", line 11, in <module>
    tfnet = TFNet(option)
  File "C:\Users\Hakan\Desktop\object\darkflow-master\darkflow\net\build.py", line 58, in __init__
    darknet = Darknet(FLAGS)
  File "C:\Users\Hakan\Desktop\object\darkflow-master\darkflow\dark\darknet.py", line 13, in __init__
    self.get_weight_src(FLAGS)
  File "C:\Users\Hakan\Desktop\object\darkflow-master\darkflow\dark\darknet.py", line 47, in get_weight_src
    '{} not found'.format(FLAGS.load)
AssertionError: bin/yolov2.weights not found

How can solve this error ?

**Comment by astaroth106** [comment]
Well your error seems to be telling you that your weights file isn't in the bin/ directory. 
I can think of some possible problems if you do have your weights in there.
1. Since you are using Windows you maybe the forwardslash (/) is the problem so you should be using backslash instead (\).
2. There are some shortcuts implemented in YOLO that will try to find the weights related to the config file, so make sure that your yolo.cfg is called yolov2.cfg.

**Comment by H4k4n61** [comment]
I try bin\yolov2.weights give same error.  I don't understand part 2. Do you want to change the name of the yolo.cfg file to yolov2.cfg ? If say that I try don't work

**Comment by H4k4n61** [comment]
Solve the problem . Windows not give access permit.

**Comment by kkwong95** [comment]
> Solve the problem . Windows not give access permit.

Can I know how you do that? I really need the solution
