### ISSUE TITLE
What are the rules to create a good dataset ?

### ISSUE THREAD

**Issue by kamelbouyacoub** [thtrieu/darkflow#90]
Hello 

I am trying to create a dataset of images, but I don't know how to create a good dataset that allow me to have a good deep neural network after training, IF it existe some rules or steps. Can you please explain to me this rules.

Thanks

**Comment by thtrieu** [comment]
A dataset is a finite sample from the real distribution of data. Just simply sample from this distribution, say, you are collected data to train a self-driving car to recognize cars and pedestrians running on street, then you simply run on the street and take pictures as if you were the car. When you are able to sample from the true distribution, collect as many data as possible.

Then annotation, since YOLO does not explicitly model false labeling, so try to be correct in all the data sample of your dataset. Annotation in the PASCAL VOC format would make later work easier since `darkflow` is built to deal with such format.

Then designing and training your net. This is a dark art, there is a lot of courses out there about what you should do with a convolution net. CS231n would give a lot of useful advices.

Good luck.
