### ISSUE TITLE
BAD OUTPUT RESULTS

### ISSUE THREAD

**Issue by alishibli97** [thtrieu/darkflow#942]
After I tried for hours training on my own dataset, I got bad output.
I am training against 1 object. I changed the labels.txt file to include 1 label object "nest" (my object), and in the cfg files, I copied the yolo.cfg file and just changed last layer to classes=1 and filters=30.
However after an iteration, the loss went down to 0. something, and the testing images showed bad results. It showed boxes all over the picture with nest as a label "nest".
Any idea why? ANY HELP IS APPRECIATED, I'VE BEEN WEEKS TRYING.
Is it because it needs more training, or what?

**Comment by ankitAMD** [comment]
@alishibli97  did you get good result? what you do ?

**Comment by alishibli97** [comment]
Yes you should test starting from the last checkpoint it was my issue and changing the threshold.

**Comment by ankitAMD** [comment]
> Yes you should test starting from the last checkpoint it was my issue and changing the threshold.

i am using tiny-yolo.cfg and tiny-yolo.weights because i have not enough RAM(only 8 GB). i train on that cfg and weight file , i am using epoch 1500 .....the losss becomes 1.**

 so i am testing the generated .pb and .meta file ....the object are detected but for first images i used thershold 0.3 but  for second images on same images it not detected anything  afterthat i am changing threshold 2.57 so object are detected on second images. 

My question is that what i have  do to detect object of given class on all images  at one threshold ??
what should i missing in the concept ? could you guide me ? 

thank you for helping.
